apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "app-frontend.fullname" . }}
  labels:
    {{- include "app-frontend.labels" . | nindent 4 }}
spec:
  parentRefs:
    - name: gateway
      namespace: istio-system
  hostnames: [{{ join "\", \"" .Values.hosts | printf "\"%s\"" }}]
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "app-frontend.fullname" . }}
          port: {{ .Values.service.port }}
