# Default values for app-frontend.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: ghcr.io/finure/app-frontend
  tag: 1.4.5
  pullPolicy: IfNotPresent
secretName: "finure-app"
frontend:
  replicas: 1
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
podAnnotations: {}
podLabels: {}
imagePullSecrets:
  - name: "ghcr"
livenessProbe:
  exec:
    command: ["/bin/sh", "/app/probe.sh"]
  initialDelaySeconds: 30
  periodSeconds: 30
  timeoutSeconds: 5
readinessProbe:
  exec:
    command: ["/bin/sh", "/app/probe.sh"]
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
service:
  type: ClusterIP
  port: 80
hosts:
  - finure.clokesh.me
